# App name
spring.application.name=docflow-backend

# Server port
server.port=8081

# JPA Settings (no credentials here)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# GraphQL settings
spring.graphql.graphiql.enabled=true

# CORS
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.allowed-headers=*

spring.jpa.open-in-view=false