# App name
spring.application.name=docflow-backend

# Server port
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/docflowdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=docflow_user
spring.datasource.password=docflow123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# GraphQL settings
spring.graphql.graphiql.enabled=true

# Allow GraphQL endpoint to handle CORS preflight
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.allowed-headers=*