# App name
spring.application.name=docflow-backend

# Server port
server.port=8081

# H2 in-memory database (temporary - Day 1 to Day 3)
spring.datasource.url=jdbc:h2:mem:docflowdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (lets you see DB in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# GraphQL settings
spring.graphql.graphiql.enabled=true